site_name: Nighttime Imaging 'N' Astronomy
site_url: https://www.nighttime-imaging.eu
site_description: An astrophotography suite designed for all DSO imagers.
site_author: N.I.N.A. contributors

repo_url: https://bitbucket.org/Isbeorn/nina/
repo_name: Bitbucket

nav:
    - Documentation:
        - Introduction: 'index.md'
        - Requirements: 'requirements.md'        
        - Tabs:
            - Overview: 'tabs/overview.md'
            - Equipment: 
                - Equipment: 'tabs/equipment/equipment.md'
                - Camera: 'tabs/equipment/camera.md'
                - Filterwheel: 'tabs/equipment/filterwheel.md'
                - Focuser: 'tabs/equipment/focuser.md'
                - Rotator: 'tabs/equipment/rotator.md'
                - Telescope: 'tabs/equipment/telescope.md'
                - Guider: 'tabs/equipment/guider.md'
                - Switch: 'tabs/equipment/switch.md'
                - Flat Panel: 'tabs/equipment/flatpanel.md'
                - Weather: 'tabs/equipment/weather.md'
                - Dome: 'tabs/equipment/dome.md'
            - Sky Atlas: 'tabs/skyatlas.md'
            - Framing Assistant: 'tabs/framing.md'
            - Flat Wizard: 'tabs/flatwizard.md'
            - Sequence Builder: 'tabs/sequencebuilder.md'
            - Sequencer: 'tabs/sequencer.md'
            - Imaging: 'tabs/imaging.md'
            - Options:
                - General: 'tabs/options/general.md'
                - Equipment: 'tabs/options/equipment.md'
                - Imaging: 'tabs/options/imaging.md'
                - Plate Solving: 'tabs/options/platesolving.md'
                - Dome: 'tabs/options/dome.md'
        - Advanced Topics:
            - Plate Solving: 'advanced/platesolving.md'
            - Object Browser: 'advanced/objectbrowser.md'
            - Guiding: 'advanced/guiding.md'
            - Dithering: 'advanced/dithering.md'
            - Framing Assistant: 'advanced/framingassistant.md'
            - Automated Meridian Flip: 'advanced/meridianflip.md'
            - Advanced Sequencing: 'advanced/advancedsequence.md'
            - Bulb Shutter Control: 'advanced/bulbshutter.md'
            - Auto-Focus: 'advanced/autofocus.md'
            - Focuser Backlash Measurement: 'advanced/backlashmeasurement.md'
            - File Formats:
                - TIFF: 'advanced/file_formats/tiff.md'
                - FITS: 'advanced/file_formats/fits.md'
                - XISF: 'advanced/file_formats/xisf.md'
        - Troubleshooting:
            - General: 'troubleshooting/general.md'
            - iOptron Mount Setup: 'troubleshooting/ioptron.md'
            - EQMOD Setup: 'troubleshooting/eqmod.md'
            - Altair Dual Gain: 'troubleshooting/altair_dualgain.md'
            - Planetarium Setup: 'troubleshooting/planetarium.md'            
        - Glossary: 'glossary.md'
        - License: 'license.md'
        - 3rd-Party-Licenses: '3rd-party-license.md'
    - Quick Start:
        - UI Overview: 'quickstart/uioverview.md'
        - Connecting Your Equipment: 'quickstart/equipment.md'
        - Finalizing Settings: 'quickstart/settings.md'
        - Focusing: 'quickstart/focusing.md'
        - Starting a Sequence: 'quickstart/sequence.md'
    - Contributing:
        - Enhance documentation: 'contributing/contributing.md'
        - How to setup the development environment: 'contributing/howtosetupdev.md'
        - Localization: 'contributing/localization.md'

theme:
    name: 'material'
    logo: 'images/nina-icon.png'
    palette:
        primary: 'indigo'
        accent: 'teal'
    feature:
        tabs: true

markdown_extensions:
    - toc:
        permalink: '#'
    - admonition
    - attr_list
    - codehilite:
        guess_lang: false
    - def_list
    - footnotes
    - meta
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details    
    - pymdownx.keys
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

copyright: Copyright &copy; 2019-2020 Stefan Berg and the N.I.N.A. contributors
